#!/bin/sh
#
# thin-server  init file for starting up the oculus webserver daemon
#
# chkconfig:   - 20 80

# Source function library.
. /etc/rc.d/init.d/functions

PATH=/usr/local/rvm/gems/ruby-1.9.2-p330/bin:/usr/local/rvm/gems/ruby-1.9.2-p330@global/bin:/usr/local/rvm/rubies/ruby-1.9.2-p330/bin:/usr/local/rvm/bin:/usr/bin:/sbin:/bin:/usr/sbin
GEM_HOME=/usr/local/rvm/gems/ruby-1.9.2-p330
IRBRC=/usr/local/rvm/rubies/ruby-1.9.2-p330/.irbrc
MY_RUBY_HOME=/usr/local/rvm/rubies/ruby-1.9.2-p330
GEM_PATH=/usr/local/rvm/gems/ruby-1.9.2-p330:/usr/local/rvm/gems/ruby-1.9.2-p330@global
RUBY_VERSION=ruby-1.9.2-p330

export PATH GEM_HOME IRBRC MY_RUBY_HOME GEM_PATH RUBY_VERSION


pidfile="/var/run/oculus/thin.pid"
logfile="/var/log/oculus/web.log"
lockfile="/var/lock/subsys/thin"
exec="/usr/local/rvm/gems/ruby-1.9.2-p330/bin/thin"
param=" -P ${pidfile} -l ${logfile} -d -c /opt/oculus -p 80 "

start() {
    [ -x $exec ] || exit 5
    cd /opt/oculus
    echo -n $"Starting `basename $exec`: "
    daemon "$exec ${param} start"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping `basename $exec`: "
    #killproc -p $pidfile `basename $exec`
    killproc -p $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    stop
    start
}

rh_status() {
    #status -p $pidfile `basename $exec`
    status -p $pidfile 
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
